### ISSUE TITLE
Add filter range status

### ISSUE THREAD

**Issue by cedvan** [BedrockStreaming/LogBridgeBundle#34]
``` yaml
filters:
    bad_requests:
        route: ~
        method: ~
        status: [~400]  # All 400 errors (400, 401, 402, ..., 499)
        level: error
        options:
            post_parameters: true
            response_body: true

    errors:
        route: ~
        method: ~
        status: [500-545]  # All errors 500 to 545  (500, 501, 502, ..., 545)
        level: critical
        options:
            post_parameters: true
            response_body: true
```
