### ISSUE TITLE
Too many logs are matched with the `route` configuration

### ISSUE THREAD

**Issue by shavounet** [BedrockStreaming/LogBridgeBundle#76]
## Description

* Since `v10.1.0`

While using a filter with `route`, every 200 POST request will be matched
```yaml
m6_web_log_bridge:
    filters:
        request:
            route: some_route
            method: [ 'POST' ]
            status: [ '2*' ]
            level: 'notice'
```

## Workaround

Use `routes`

```yaml
m6_web_log_bridge:
    filters:
        request:
            routes: [ some_route ]
            method: [ 'POST' ]
            status: [ '2*' ]
            level: 'notice'
```
